# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materialprice', '0009_auto_20161123_1420'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materialprice',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='smm',
            unique_together=set([('designation', 'pricedate')]),
        ),
    ]
