# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materialprice', '0010_auto_20161123_1441'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='smm',
            unique_together=set([]),
        ),
    ]
